<?xml version="1.0"?>
<package format="2">
    <name>plan_admin</name>
    <version>0.0.0</version>
    <description>planning administrator of mogen ros</description>

    <maintainer email="jaimefriedhelmzhao@gmail.com">Zhaohong Liu</maintainer>

    <license>TODO</license>

    <buildtool_depend>catkin</buildtool_depend>
    <build_depend>roscpp</build_depend>
    <build_depend>rospy</build_depend>
    <build_depend>std_msgs</build_depend>
    <build_depend>mavros_msgs</build_depend>
    <build_depend>map_utils</build_depend>
    <build_depend>rviz_utils</build_depend>
    <build_depend>frontend_searcher</build_depend>
    <build_depend>backend_optimizer</build_depend>

    <build_export_depend>roscpp</build_export_depend>
    <build_export_depend>rospy</build_export_depend>
    <build_export_depend>std_msgs</build_export_depend>
    <build_export_depend>mavros_mags</build_export_depend>

    <exec_depend>roscpp</exec_depend>
    <exec_depend>rospy</exec_depend>
    <exec_depend>std_msgs</exec_depend>
    <exec_depend>mavros_msgs</exec_depend>
    <exec_depend>map_utils</exec_depend>
    <exec_depend>rviz_utils</exec_depend>
    <exec_depend>frontend_searcher</exec_depend>
    <exec_depend>backend_optimizer</exec_depend>

    <!-- The export tag contains other, unspecified, tags -->
    <export>
        <!-- Other tools can request additional information be placed here -->

    </export>
</package>
